name: "CD pipline"

on:
    workflow_run:
        workflows: ["sample React CI Pipline / Workflow "]
        types:
            - completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production #You need to metion in which env you need to run this
        
        steps:
         
        - name: "Setup NodeJs"
          uses: actions/setup-node@v4
          with:
             node-version: '21'

        - name: "Setup vercel Cli"
          run: npm install -g vercel

        - name: "Download build files"
          uses: actions/download-artifact@v4
          with:
            name: build
            run-id: ${{github.event.workflow_run.id}}
            github-token: ${{ github.token }}


        - name: "Deploy of vercel"
          run: vercel --prod --token=${{ secrets.VERCEL_TOKEN}} --confirm --name=CiCdproject
          #env: 
           #VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }